<a href="https://colab.research.google.com/github/KeerthiSegu/DataScience-Assignments_Repository/blob/main/Numpy_assignment(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Import the numpy package under the name np 

In [71]:
import numpy as np

# Print the numpy version and the configuration 


In [72]:
print(np.__version__)

1.22.4


# Create a null vector of size 20 

In [73]:
data=np.zeros(20)
data

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

# How to find the memory size of any array 

In [74]:
print("Size of the array: ",data.size)
print("Memory size of one array element in bytes: ",data.itemsize)
print("Memory size of numpy array in bytes:",data.size * data.itemsize)# memory size of numpy array

Size of the array:  20
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 160


# How to get the documentation of the numpy add function from the command line? 

In [75]:
import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# Create a null vector of size 20 but the fifth value which is 1 

In [76]:
data=np.zeros(20)
print(data)
data[4]=1
data

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

# Create a vector with values ranging from 10 to 68 

In [77]:
data=np.arange(10,69)
data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68])

# Reverse a vector (first element becomes last) 

In [78]:
data[::-1]

array([68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52,
       51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35,
       34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18,
       17, 16, 15, 14, 13, 12, 11, 10])

# Create a 3x3 matrix with values ranging from 0 to 10

In [79]:
data=np.random.randint(0,11,(3,3))
data

array([[6, 4, 2],
       [5, 4, 6],
       [2, 9, 2]])

# Find indices of non-zero elements from [0,2,1,0,4,0] 

In [80]:
x=np.nonzero([0,2,1,0,4,0])
x

(array([1, 2, 4]),)

# Create a 3x3 identity matrix 

In [81]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 3x3x3 array with random values


In [82]:
np.random.randint(1,10,(3,3,3))

array([[[8, 6, 1],
        [8, 9, 9],
        [9, 1, 8]],

       [[3, 1, 8],
        [2, 2, 6],
        [2, 6, 7]],

       [[5, 9, 8],
        [6, 2, 9],
        [1, 6, 4]]])

#  Create a 10x10 array with random values and find the minimum and maximum values 

In [83]:
data=np.random.randint(30,500,(101,10))
print(data)
print("Minimum value",data.min())
print("Maximum value",data.max())

[[426 183 363 ... 464 354 161]
 [216  42 160 ... 429 386 360]
 [426 432 188 ... 126 474 457]
 ...
 [328 102  61 ... 166 347  53]
 [320 281 161 ... 310  92 136]
 [151  56 128 ... 245 269 492]]
Minimum value 30
Maximum value 499


# Create a random vector of size 30 and find the mean value 

In [84]:
data=np.arange(30)
print("Mean",data.mean())

Mean 14.5


# Create a 2d array with 1 on the border and 0 inside 


In [85]:
data=np.ones((3,3))
data[1,1]=0
data


array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [86]:
data=np.ones((5,5))
data[1:4,1:4]=0
data

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# How to add a border (filled with 0's) around an existing array? 

In [87]:
data=np.random.randint(2,20,(3,3))
print(data)
data=np.pad(data,pad_width=1,mode='constant',constant_values=0)
data

[[19 17  5]
 [11 16  4]
 [14  2  3]]


array([[ 0,  0,  0,  0,  0],
       [ 0, 19, 17,  5,  0],
       [ 0, 11, 16,  4,  0],
       [ 0, 14,  2,  3,  0],
       [ 0,  0,  0,  0,  0]])

# What is the result of the following expression? 

In [88]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [89]:
data=np.diag([1,2,3,4],-1)
data

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# Create a 8x8 matrix and fill it with a checkerboard pattern 


In [90]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Create a checkerboard 8x8 matrix using the tile function 


In [91]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix 

In [92]:
data=np.random.randint(10,20,(5,5))
normatrix=((data-(data.min()))/((data.max())-(data.min())))
normatrix

array([[0.125, 0.875, 0.25 , 0.625, 1.   ],
       [0.75 , 0.875, 0.625, 1.   , 1.   ],
       [1.   , 0.875, 0.125, 0.   , 0.625],
       [0.375, 1.   , 0.25 , 0.   , 0.25 ],
       [0.625, 0.5  , 0.375, 1.   , 0.625]])

# Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [93]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])

<ipython-input-93-42443a84e1a2>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),


# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [94]:
x=np.random.randint(10,20,(5,3))
y=np.random.randint(1,5,(3,2))
np.dot(x,y)

array([[132,  90],
       [154, 109],
       [156, 108],
       [154, 107],
       [156, 110]])

# Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [95]:
data=np.arange(12)
data[(3<data)&(data<8)]*=-1
data

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

# What is the output of the following script? 

In [131]:
#print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


# Consider an integer vector Z, which of these expressions are legal? 

In [98]:
z=np.arange(1,12)
print(z**z)
print(2<<z>>2)
print(z<-z)
print(1j*z)
print(z/1/1)
#print(z<z>z) # It is not legal

[           1            4           27          256         3125
        46656       823543     16777216    387420489  10000000000
 285311670611]
[   1    2    4    8   16   32   64  128  256  512 1024]
[False False False False False False False False False False False]
[0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j 0. +9.j
 0.+10.j 0.+11.j]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


# What are the result of the following expressions? 


In [99]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-99-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-99-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


# How to find common values between two arrays? 


In [100]:
arr1=np.array([2,3,4,56,67])
arr2=np.array([56,57,58,67,3,4,5])
arr=intersect1d(arr1,arr2,assume_unique=True)
arr

array([ 3,  4, 56, 67])

# How to ignore all numpy warnings (not recommended)? 

In [101]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

# Is the following expressions true? 


In [102]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-102-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

# How to get the dates of yesterday, today and tomorrow? 

In [104]:
from datetime import datetime
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
Today=np.datetime64('today','D')
Tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Yesterday",yesterday)
print("Today",Today)
print("Tomorrow",Tomorrow)

Yesterday 2023-05-13
Today 2023-05-14
Tomorrow 2023-05-15


# How to get all the dates corresponding to the month of July 2016? 


In [103]:
import numpy as np
date = np.array('2016-07-01', dtype=np.datetime64)
date
np.arange(31)
date + np.arange(31)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

# Extract the integer part of a random array of positive numbers using 4 different methods 

In [105]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4. 5. 1. 3. 1. 7. 4. 4. 8. 5.]
[4. 5. 1. 3. 1. 7. 4. 4. 8. 5.]
[4. 5. 1. 3. 1. 7. 4. 4. 8. 5.]
[4 5 1 3 1 7 4 4 8 5]
[4. 5. 1. 3. 1. 7. 4. 4. 8. 5.]


# Create a 5x5 matrix with row values ranging from 0 to 5 


In [106]:
data=np.zeros((5,5))
data+=np.arange(5)
data

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# Create a vector of size 10 with values ranging from 0 to 1, both excluded 


In [107]:
np.random.rand(10)

array([0.40909083, 0.26889202, 0.07201204, 0.41813613, 0.02575348,
       0.29115394, 0.50350951, 0.96593307, 0.10938291, 0.67304105])

# Create a random vector of size 20 and sort it 


In [108]:
z=np.random.randint(1,20,20)
print(z)
z.sort()
z

[ 3 11 16 15  2 12 13 16 19 14  2  7  2 15  1 15  2 13 17  1]


array([ 1,  1,  2,  2,  2,  2,  3,  7, 11, 12, 13, 13, 14, 15, 15, 15, 16,
       16, 17, 19])

# How to sum a small array faster than np.sum? 


In [109]:
arr=np.random.randint(2,20,5)
print(arr)
np.add.reduce(arr)

[15 15  6 12 15]


63

# Consider two random array A and B, check if they are equal 


In [110]:
a=np.random.randint(1,10,10)
print(a)
b=np.random.randint(1,10,10)
print(b)
np.array_equal(a,b)

[9 8 4 2 1 6 8 2 5 9]
[5 3 2 4 2 8 8 1 8 3]


False

# Make an array immutable (read-only) 

In [111]:
a=np.random.randint(1,10,4)
a.flags.writeable=False
print(a)
a[3]=6
print(a)

[4 5 1 5]


ValueError: ignored

# Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [112]:
np.random.seed(1)
data=np.random.randint(1,10,(5,2))
print(data)
x = data[0:,0:1]
y=data[0:,1:2]
r=np.sqrt(x**2+y**2)
print(r)
w=np.arctan(y/x)
print(w)



[[6 9]
 [6 1]
 [1 2]
 [8 7]
 [3 5]]
[[10.81665383]
 [ 6.08276253]
 [ 2.23606798]
 [10.63014581]
 [ 5.83095189]]
[[0.98279372]
 [0.16514868]
 [1.10714872]
 [0.71883   ]
 [1.03037683]]


# Create random vector of size 20 and replace the maximum value by 0 


In [113]:
np.random.seed(1)
data=np.random.randint(1,40,20)
print(data)
print(data.max())
data[data.argmax()]=0
data



[38 13  9 10 12  6 16  1 17  2 13  8  7 26 21 38 19 21 12 29]
38


array([ 0, 13,  9, 10, 12,  6, 16,  1, 17,  2, 13,  8,  7, 26, 21, 38, 19,
       21, 12, 29])

# Print the minimum and maximum representable value for each numpy scalar type 

In [114]:
for i in (np.int8,np.int16,np.int32,np.int64):
  print(np.iinfo(i).max)
  print(np.iinfo(i).min)
for i in (np.float32,np.float64):
  print(np.finfo(i).max)
  print(np.finfo(i).min)

127
-128
32767
-32768
2147483647
-2147483648
9223372036854775807
-9223372036854775808
3.4028235e+38
-3.4028235e+38
1.7976931348623157e+308
-1.7976931348623157e+308


# How to print all the values of an array? 


In [115]:
arr=np.random.randint(1,10,(5,5))
[i for i in arr]

[array([3, 5, 8, 8, 2]),
 array([8, 1, 7, 8, 7]),
 array([2, 1, 2, 9, 9]),
 array([4, 9, 8, 4, 7]),
 array([6, 2, 4, 5, 9])]

# How to convert a float (32 bits) array into an integer (32 bits) in place

In [116]:
arr=np.arange(1,10,dtype=float32)
print(arr)
arr.astype('i')

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

# How to randomly place p elements in a 2D array? 

In [117]:
n = 10
p = 5
data= np.zeros((n,n))
np.put(data, np.random.choice(range(n*n), p),10)
print (data)


[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.]
 [10.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


# Subtract the mean of each row of a matrix 


In [118]:
np.random.seed(1)
data=np.random.randint(1,10,(5,5))
x=data.mean(axis=1)
print(data)
print(x)
print((data-x))

[[6 9 6 1 1]
 [2 8 7 3 5]
 [6 3 5 3 5]
 [8 8 2 8 1]
 [7 8 7 2 1]]
[4.6 5.  4.4 5.4 5. ]
[[ 1.4  4.   1.6 -4.4 -4. ]
 [-2.6  3.   2.6 -2.4  0. ]
 [ 1.4 -2.   0.6 -2.4  0. ]
 [ 3.4  3.  -2.4  2.6 -4. ]
 [ 2.4  3.   2.6 -3.4 -4. ]]


# How to sort an array by the nth column? 

In [119]:
n=int(input("Enter number :"))
data=np.random.randint(1,10,(5,5))
print(data)
data[data[:,n].argsort()]


Enter number :4
[[2 9 9 4 9]
 [8 4 7 6 2]
 [4 5 9 2 5]
 [1 4 3 1 5]
 [3 8 8 9 7]]


array([[8, 4, 7, 6, 2],
       [4, 5, 9, 2, 5],
       [1, 4, 3, 1, 5],
       [3, 8, 8, 9, 7],
       [2, 9, 9, 4, 9]])

# How to tell if a given 2D array has null columns? 


In [120]:
data=np.random.randint(1,10,(3,3))
print(data)
print((~data.any(axis=0)).any())

[[4 8 8]
 [5 6 4]
 [7 9 1]]
False


# Considering a four dimensions array, how to get sum over the last two axis at once? 

In [121]:
np.random.seed(1)
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[56 54 70 59]
 [60 67 59 58]
 [57 47 56 35]]


# How to get the diagonal of a dot product? 

In [122]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print(A)
print(B)
np.diag(np.dot(A, B))


[[7 8 9]
 [5 7 0]
 [9 3 9]]
[[1 4 4]
 [6 8 8]
 [9 2 7]]


array([136,  76, 123])

# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [123]:
data=np.array([1,2,3,4,5])
df=np.zeros(len(data)+(len(data)-1)*3)
df[::4]=data
df

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [124]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# How to swap two rows of an array? 


In [125]:
data=np.random.randint(1,10,(3,3))
print(data)
data[[0,2]]=data[[2,0]]
print(data)

[[6 6 5]
 [6 9 6]
 [9 2 2]]
[[9 2 2]
 [6 9 6]
 [6 6 5]]


# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [126]:
Z = np.arange(1,15,dtype=uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# Compute a matrix rank 

In [127]:
data=np.random.randint(1,10,(5,5))
np.linalg.matrix_rank(data)

5

# How to find the most frequent value in an array?


In [128]:
data=np.random.randint(1,10,50)
print(data)
a=np.bincount(data).argmax()
a

[4 9 2 5 4 4 7 8 4 6 4 3 5 5 1 4 4 9 4 6 7 8 6 2 8 1 3 9 3 2 5 1 5 2 8 4 2
 7 7 7 7 1 1 3 7 1 7 8 1 4]


4

# How to get the n largest values of an array 

In [129]:
data=np.random.randint(1,10,50)
print(data)
n=int(input())
print(data[data.argsort()])
data[data.argsort()][-n:]

[1 4 5 8 6 4 9 9 1 7 8 6 5 6 3 6 7 7 9 8 8 8 3 7 1 6 3 2 9 6 5 2 3 1 5 8 1
 7 3 5 4 7 8 7 4 1 7 5 8 7]
9
[1 1 1 1 1 1 2 2 3 3 3 3 3 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 7
 7 8 8 8 8 8 8 8 8 9 9 9 9]


array([8, 8, 8, 8, 8, 9, 9, 9, 9])